question_data = [
         {"category": "Mythology", "type": "boolean", "difficulty": "easy",
          "question": "In Norse mythology, Thor once dressed as a woman.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "The Great Wall of China is visible from the moon.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "San Marino is the only country completely surrounded by another country.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
          "difficulty": "easy",
          "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "There is a city called Rome in every continent on Earth.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
          "question": "The communication protocol NFC stands for Near-Field Control.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
          "difficulty": "easy",
          "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "Ottawa is the capital of Canada.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Politics", "type": "boolean", "difficulty": "easy",
          "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Politics", "type": "boolean", "difficulty": "easy",
          "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "You can legally drink alcohol while driving in Mississippi.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
          "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
          "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "Toronto is the capital city of the North American country of Canada.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
          "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "Daft Punk originated in France.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "easy",
          "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "easy",
          "question": "Adolf Hitler was tried at the Nuremberg trials.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "Scatman John&#039;s real name was John Paul Larkin.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Sports", "type": "boolean", "difficulty": "easy",
          "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
          "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Geography", "type": "boolean", "difficulty": "easy",
          "question": "Rhode Island is actually located on the US mainland, despite its name.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
          "question": "An equilateral triangle always has every angle measuring 60&deg;.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "Slovakia is a member of European Union-", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Animals", "type": "boolean", "difficulty": "easy",
          "question": "Rabbits are carnivores.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Animals", "type": "boolean", "difficulty": "easy",
          "question": "The internet browser Firefox is named after the Red Panda.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
          "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "The mitochondria is the powerhouse of the cell.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
          "question": "Ping-Pong originated in England", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
          "correct_answer": "False", "incorrect_answers": ["True"]}
]
